In [1]:
#BASIC CALCULATION
import numpy as np
a= np.array([1.1,1.5,1.9],float)
print(np.sqrt(a))
print(np.floor(a), '#give the lower rounded integer')
print(np.ceil(a), '#give the upper rounded integer')
print(np.rint(a), '#give the nearest rounded integer')

[1.04880885 1.22474487 1.37840488]
[1. 1. 1.] #give the lower rounded integer
[2. 2. 2.] #give the upper rounded integer
[1. 2. 2.] #give the nearest rounded integer


In [2]:
#mathematical constant
print(np.pi)
print(np.e)

3.141592653589793
2.718281828459045


In [8]:
#ARRAY ITERATION
a=np.array([1,4,5],int)
for x in a:
    print(x)
b=np.array([[1,3,5], [3,8,5],[2,7,5]],int)
for y in b:
    print(y)
for (x,y,z)in b:
    print(x*y*z)

1
4
5
[1 3 5]
[3 8 5]
[2 7 5]
15
120
70


In [10]:
#BASIC ARRAY OPERATIONS
a=np.array([1,2,5],float)
print(a.sum(), "\t#sum of the values")
print(a.prod(),"\t#product of the values")
print(np.sum(a), "\t #another function for sum ")
print(a.mean(), "\t#average")
print(a.var(), "\t#variance")
print(a.std(), "\t#vstandard deviation")
print(a.min(), "\t#minimum value")
print(a.max(), "\t#maximum value")
print(a.argmin(), "\t#indices of the minimum value")
print(a.argmax(), "\t#indices of the maximum value")

8.0 	#sum of the values
10.0 	#product of the values
8.0 	 #another function for sum 
2.6666666666666665 	#average
2.8888888888888893 	#variance
1.699673171197595 	#vstandard deviation
1.0 	#minimum value
5.0 	#maximum value
0 	#indices of the minimum value
2 	#indices of the maximum value


In [12]:
#MULTIDIMENSIONAL
a=np.array([[0,2],[3,6],[-1,7]],float)
print(a.mean(axis=0))
print(a.mean(axis=1))
print(a.min(axis=1))
print(a.max(axis=0))

[0.66666667 5.        ]
[1.  4.5 3. ]
[ 0.  3. -1.]
[3. 7.]


In [16]:
#SORTing
a=np.array([2.1,3.7,6.4,1.9,4.2],float)
print(sorted(a))
a.sort()
print(a)
#CLIPPING
a=np.array([2.1,3.7,6.4,1.9,4.2],float)
print(a.clip(1.2,4.2))

[1.9, 2.1, 3.7, 4.2, 6.4]
[1.9 2.1 3.7 4.2 6.4]
[2.1 3.7 4.2 1.9 4.2]


In [2]:
import numpy as np
#Extracting Unique Element
a=np.array([1,2,1,4,5,5,5,4,7],float)
print(np.unique(a))

#diagonal
a=np.array([[1,4],[0,3]],int)
print(a.diagonal())

[1. 2. 4. 5. 7.]
[1 3]


In [3]:
#COMPARISON OPERATORS AND VALUE TESTING
a=np.array([1,3,0],float)
b=np.array([0,3,5],float)
print(a>b)
print(a==b)
print(a<=b)

#storing result of booleen comparison
c=a>b
print(c)
print(a>2)

[ True False False]
[False  True False]
[False  True  True]


In [1]:
#ANY and ALL
import numpy as np
c=np.array([True,False,False],bool)
print(any(c))
print(all(c))

True
False


In [2]:
#logical_and, logical_or and logical_not
import numpy as np
a=np.array([1,3,0],float)
print(np.logical_and(a>0,a<3))
b=np.array([True, False, False],bool)
print(np.logical_not(b))
c=np.array([False,True,False],bool)
print(np.logical_or(b,c))

[ True False False]
[False  True  True]
[ True  True False]


In [3]:
#WHERE
#where(boolarray,truearray,falsearray)
a=np.array([1,3,0],float)
print(np.where(a!=0,1/a,a))
#broadcasting
print(np.where(a>0,3,2))

[1.         0.33333333 0.        ]
[3 3 2]


c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


In [8]:
#testing
a=np.array([1,np.NaN,np.inf],float)
print(a)
print(np.isnan(a))
print(np.isfinite(a))
print(np.isinf(a))

a=np.array([[2,1],[0,3]],float)
print(a.nonzero())
b=np.array([[3,2,1],[0,1,3],[4,0,0]],float)
print(b.nonzero())

[ 1. nan inf]
[False  True False]
[ True False False]
[False False  True]
(array([0, 0, 1], dtype=int32), array([0, 1, 1], dtype=int32))
(array([0, 0, 0, 1, 1, 2], dtype=int32), array([0, 1, 2, 1, 2, 0], dtype=int32))


In [10]:
#Array Item selection and manipulation
a=np.array([[6,4],[5,9]],float)
print(a>=6)
print(a[a>=6])
print(a[np.logical_and(a>5,a<9)])


[[ True False]
 [False  True]]
[6. 9.]
[6.]


In [11]:
a=np.array([2,4,6,8],float)
b=np.array([0,0,1,3,2,1],int)
print(a[b])
a=np.array([2,4,6,8],float)
print(a[[0,0,1,3,2,1]])

[2. 2. 4. 8. 6. 4.]
[2. 2. 4. 8. 6. 4.]


In [13]:
a=np.array([[1,4],[9,16]],float)
b=np.array([0,0,1,1,0],int)
c=np.array([0,1,1,1,1],int)
print(a[b,c])

[ 1.  4. 16. 16.  4.]


In [4]:
#take
import numpy as np
a=np.array([2,4,6,9],float)
b=np.array([0,0,1,3,2,1],int)
print(a.take(b))
a=np.array([[0,1],[2,3]],float)
b=np.array([0,0,1],int)
print(a.take(b, axis=0))
print(a.take(b, axis=1))

[2. 2. 4. 9. 6. 4.]
[[0. 1.]
 [0. 1.]
 [2. 3.]]
[[0. 0. 1.]
 [2. 2. 3.]]


In [7]:
#put
a=np.array([0,1,2,3,4,5],float)
b=np.array([9,8,7],float)
a.put([0,3],b)
print(a)
a=np.array([0,1,2,3,4,5],float)
a.put([0,3],5)
print(a)

[9. 1. 2. 8. 4. 5.]
[5. 1. 2. 5. 4. 5.]
