In [2]:
#VECTOR AND MATRIX MATHEMATICS
import numpy as np
a=np.array([1,2,3],float)
b=np.array([0,1,1],float)
print(np.dot(a,b))

5.0


In [4]:
#dot to matrix multiplication
a=np.array([[0,1],[2,3]],float)
b=np.array([2,3],float)
c=np.array([[1,1],[4,0]],float)
print(np.dot(a,b))
print(np.dot(b,a))
print(np.dot(a,c))


[ 3. 13.]
[ 6. 11.]
[[ 4.  0.]
 [14.  2.]]


In [5]:
#inner #outer #cross
#inner is equivalent to dot product
a=np.array([1,4,0],float)
b=np.array([2,2,1],float)
print(np.outer(a,b))
print(np.inner(a,b))
print(np.cross(a,b))

[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
10.0
[ 4. -1. -6.]


In [6]:
#determinant
a=np.array([[4,2,0],[9,3,7],[1,2,1]],float)
print(a)
print(np.linalg.det(a))

#eigenvalue and eigenvector
vals,vecs=np.linalg.eig(a)
print(vals)
print(vecs)

[[4. 2. 0.]
 [9. 3. 7.]
 [1. 2. 1.]]
-48.00000000000003
[ 8.85591316  1.9391628  -2.79507597]
[[-0.3663565  -0.54736745  0.25928158]
 [-0.88949768  0.5640176  -0.88091903]
 [-0.27308752  0.61828231  0.39592263]]


In [7]:
#inverse
a=np.array([[4,2,0],[9,3,7],[1,2,1]],float)
b=np.linalg.inv(a)
print(b)
print(np.dot(a,b))

[[ 0.22916667  0.04166667 -0.29166667]
 [ 0.04166667 -0.08333333  0.58333333]
 [-0.3125      0.125       0.125     ]]
[[1.00000000e+00 5.55111512e-17 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 2.22044605e-16]
 [0.00000000e+00 1.38777878e-17 1.00000000e+00]]


In [5]:
import numpy as np
A=np.mat('[1,3;4,7]')
print(A.I)
print(A.T)
b=np.mat('[2,5;4,7;9,0]')
c=b.A
print(c)

[[-1.4  0.6]
 [ 0.8 -0.2]]
[[1 4]
 [3 7]]
[[2 5]
 [4 7]
 [9 0]]


In [7]:
#solving a linear system
import numpy as np
from scipy import linalg
A=np.array([[1,3,5],[2,5,1],[2,3,8]],int)
print(A)
B=np.array([10,8,3],int)
print(B)
c_inv=linalg.inv(A)
print(c_inv)
sol=c_inv.dot(B.T)
sol2=np.linalg.solve(A,B.T)
print("the solution of equation is;",sol)
print("the fast solution of equation is;",sol2)

[[1 3 5]
 [2 5 1]
 [2 3 8]]
[10  8  3]
[[-1.48  0.36  0.88]
 [ 0.56  0.08 -0.36]
 [ 0.16 -0.12  0.04]]
the solution of equation is; [-9.28  5.16  0.76]
the fast solution of equation is; [-9.28  5.16  0.76]


In [8]:
#singular value decomposition
a=np.array([[1,3,4],[5,2,3]],float)
U,s,Vh=np.linalg.svd(a)
print(U)
print(s)
print(Vh)

[[-0.6113829  -0.79133492]
 [-0.79133492  0.6113829 ]]
[7.46791327 2.86884495]
[[-0.61169129 -0.45753324 -0.64536587]
 [ 0.78971838 -0.40129005 -0.46401635]
 [-0.046676   -0.79349205  0.60678804]]


In [5]:
#POLYNOMIAL
import numpy as np
a=np.poly([-1,1,1,10])
print(a)
b=np.roots([1,4,-2,3])
print(b)

"""
integrating polynomial
"""
print(np.polyint([1,1,1,1]))

"""differentiating polynomial"""
print(np.polyder([1./4.,1./3.,1./2.,1.,0.]))

[  1. -11.   9.  11. -10.]
[-4.5797401 +0.j          0.28987005+0.75566815j  0.28987005-0.75566815j]
[0.25       0.33333333 0.5        1.         0.        ]
[1. 1. 1. 1.]


In [9]:
#basic operation 
print("addition:", np.polyadd([1,3,2],[2,0,5]))
print("subtraction:", np.polysub([1,3,2],[2,0,5]))
print("multiplication:", np.polymul([1,3,2],[2,0,5]))
print("division:", np.polydiv([1,3,2],[2,0,5]))

print("evaluating a polynomial")
print(np.polyval([1,-2,0,2],4))

print("fitting a polynomial least square")
x=[1,2,3,4,5,6,7,8]
y=[0,2,1,3,7,10,11,19]
print("the coeficient of the equation are;", np.polyfit(x,y,2))


addition: [3 3 7]
subtraction: [-1  3 -3]
multiplication: [ 2  6  9 15 10]
division: (array([0.5]), array([ 3. , -0.5]))
evaluating a polynomial
34
fitting a polynomial least square
the coeficient of the equation are; [ 0.375      -0.88690476  1.05357143]


In [3]:
#STATISTICS
a=[]
num=float(input("Enter digit:"))
while num!="":
    a.append(num)
    num=input("next:")
b=np.array(a,float)
print(b)
print(np.sort(b))
print("median:",np.median(b))
print("mean:",np.mean(b))
print("variance:",np.var(b))
print("standard deviation:",np.std(b))
    

Enter digit:4
next:5
next:3
next:2
next:5
next:
[4. 5. 3. 2. 5.]
[2. 3. 4. 5. 5.]
median: 4.0
mean: 3.8
variance: 1.3599999999999999
standard deviation: 1.16619037896906


In [ ]:
#correlation
import numpy as np
import matplotlib.pyplot as plt
x=[]
y=[]
n=int(input("number of paired value:"))
num1=float(input("Enter x digit:"))
while len(x)<=(n-1):
    x.append(num1)
    num1=input("next:")
num2=float(input("Enter y digit:"))
while len(y)<=(n-1):
    y.append(num2)
    num2=input("next:")
print("Entry Complete as the length = n-pair")
b=np.array((x,y),float)
print(b)
def correlation(b):
    return np.corrcoef(b), np.cov(b)
np.corrcoef, np.cov = correlation(b)
print("correlation coefficient:",np.corrcoef, "covariance:",np.cov)

   


In [1]:
#Random Numbers
import numpy as np
np.random.seed(2342)
np.random.rand(5)

array([0.3527652 , 0.24368066, 0.66386938, 0.42776145, 0.4021145 ])

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Dell/Desktop/McGeorge/Tracker/Kwara LastMile'