In [10]:
#Array can be multidimensional
a=np.array([[2,4,5],[3,9,1]],float)
print(a)
print(a[0,0])
print(a[0,1])
print(a[1,:], "#to print all values in 2nd row")
print(a[:,2], "#to print all values in 3rd column")
print(a[-1:,-2:], "#to print all value in 2nd row excluding the first in second")

[[2. 4. 5.]
 [3. 9. 1.]]
2.0
4.0
[3. 9. 1.] #to print all values in 2nd row
[5. 1.] #to print all values in 3rd column
[[9. 1.]] #to print all value in 2nd row excluding the first in second


In [12]:
#Shape: returns a tuple with the size of each array
a=np.array([[2,7,5],[8,9,4]],float)
print(a.shape)

#dtype: tells you what type of values are stored by the array
print(a.dtype)

#len: return length of the first axis
print(len(a))

#in: can be used to test if a value is present in an array
print(2 in a)
print(0 in a)

(2, 3)
float64
2
True
False


In [13]:
#reshape: to reshape using tuple that specify new dimension
a=np.array(range(10),float)
print(a)
a=a.reshape(5,2)
print(a)
#the reshape function create a new array and does not itselfmodify the original array

#copy: can be used to create a new, seperate copy of an array in memory if needed
a=np.array([1,2,3],float)
b=a
c=a.copy()
a[0]=0
print(a)
print(b)
print(c)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
[0. 2. 3.]
[0. 2. 3.]
[1. 2. 3.]


In [4]:
#tolist: used to create list from arrays
a=np.array([1,2,3],float)
print(a.tolist(), "#using tolist")
print(list(a))

#tostring: used to convert the raw data into binary string
s=a.tostring()
print(s)

#fromstring: allows an array to be created from the data later on
b=np.fromstring(a)


[1.0, 2.0, 3.0] #using tolist
[1.0, 2.0, 3.0]
b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'


c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:7: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  import sys
c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:11: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  # This is added back by InteractiveShellApp.init_path()


In [22]:
#fill: to fill an array with a single value
a=np.array([1,2,3],float)
print(a)
a.fill(0)
print(a)

#transpose: create a new array with the final two axes switched
a=np.array(range(6),float).reshape(2,3)
print(a)
print(a.shape)

a=a.transpose()
print(a)
print(a.shape)

a=a.flatten()
print(a)
print(a.shape)

[1. 2. 3.]
[0. 0. 0.]
[[0. 1. 2.]
 [3. 4. 5.]]
(2, 3)
[[0. 3.]
 [1. 4.]
 [2. 5.]]
(3, 2)
[0. 3. 1. 4. 2. 5.]
(6,)


In [27]:
#Concatenate: two or more function with a tuple of array to be joined
a=np.array([1,2],float)
b=np.array([3,4,5,6],float)
c=np.array([7,8,9],float)
print(np.concatenate((a,b,c)))

#array with multiple dimension
a=np.array([[1,2],[3,4]],float)
b=np.array([[5,6],[7,8]],float)
print(np.concatenate((a,b)))
print(np.concatenate((a,b),axis=0))
print(np.concatenate((a,b),axis=1))

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
[[1. 2. 5. 6.]
 [3. 4. 7. 8.]]


In [30]:
#newaxis:increasing dimensionality
a=np.array([1,2,3,],float)
print(a[:,np.newaxis])
print(a[:,np.newaxis].shape)

[[1.]
 [2.]
 [3.]]
(3, 1)


In [32]:
#other ways to create arrays
#arange function is similar to the range function but returns an array
a=np.arange(5,dtype=float)
print(a)
b=np.arange(1,6,2,dtype=int)
print(b)

#ZEROS and ONES
a=np.ones((2,3),dtype=float)
print(a)
b=np.zeros(7,dtype=int)
print(b)

#zeros_like and ones_like functions create a new array with the same dimensions and type of an existing one
a=np.array([[1,2,3],[4,5,6]],float)
print(np.zeros_like(a))
print(np.ones_like(a))


#Identity: to create an identity matrix of a given size
a=np.identity(4,dtype=float)
print(a)

#EYE function returns matrices with ones along the kth diagonal
a=np.eye(4,k=1,dtype=float)
print(a)
a=np.eye(4,k=2,dtype=int)
print(a)

[0. 1. 2. 3. 4.]
[1 3 5]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 0 0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
[[0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]]
